<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EC2AMAZ-SFN1RDI" name="com.nbcd.Test.TCGlobalHomePage_Verify_NBCRESP_6584" tests="1" failures="1" timestamp="11 Apr 2018 05:25:04 GMT" time="46.622" errors="0">
  <testcase name="Verify_NBCRESP_6584" time="46.622" classname="com.nbcd.Test.TCGlobalHomePage_Verify_NBCRESP_6584">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.nbcd.Pages.PGGlobalHomePage.Verify_NBCRESP_6584(PGGlobalHomePage.java:2047)
at com.nbcd.Test.TCGlobalHomePage_Verify_NBCRESP_6584.Verify_NBCRESP_6584(TCGlobalHomePage_Verify_NBCRESP_6584.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Verify_NBCRESP_6584 -->
</testsuite> <!-- com.nbcd.Test.TCGlobalHomePage_Verify_NBCRESP_6584 -->
